services:
  - type: web
    name: dream-cart
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn mdc.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mdc.settings
      - key: PYTHON_VERSION
        value: 3.10

