# Generated by Django 5.1.7 on 2025-05-23 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produc',
            new_name='Product',
        ),
    ]
