# Generated by Django 5.1.7 on 2025-09-19 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orders_rename_subcategory_product_subcategory_and_more'),
    ]

    operations = [
    ]
